#!/bin/bash

RESULT=$(rg housenet.yaleman.org --no-ignore --glob '!states/' --glob '!target/' --glob '!.githooks/pre-commit' --glob '!devices.json' | sed -E '/^[[:space:]]*$/d')
LINES=$(echo "${RESULT}" | grep -cv '^$' )

if [ "$LINES" -gt 0 ]; then
    echo "Found ${LINES} references in the following files to housenet.yaleman.org, please replace them with the 'example.com' domain:"
    echo "'${RESULT}'"
    exit 2
fi

cargo clippy --quiet --all-targets || {
    echo "The above came from running cargo clippy, please review them and correct outstanding issues before continuing"
    exit 2
}

# Check JavaScript syntax
just check_js || {
    echo "JavaScript syntax check failed, please fix the issues before continuing"
    exit 2
}