#!/bin/bash

RESULT=$(rg housenet.yaleman.org --no-ignore | rg -v ./states )
LINES=$(echo "${RESULT}" | wc -l)

if [ "$LINES" -gt 0 ]; then
    echo "Found ${LINES}references to housenet.yaleman.org"
    exit 1
fi